name: DCO

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  dco-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify DCO Sign-off in PR commits
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const { data: commits } = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              per_page: 250,
            });
            const unsigned = commits.filter(c => !/Signed-off-by:/i.test(c.commit.message));
            if (unsigned.length) {
              core.setFailed(`DCO failed. ${unsigned.length} commit(s) missing Signed-off-by.`);
            }


